spring:
  application:
    name: "tx-saga-manager"
server:
  port: 8081
kafka:
  bootstrap-servers: "192.168.55.195:29092"
  topic:
    tx-request: cdc.public.transfer_tx_outbox
    balance-update-request: balance.update-request