spring:
  application:
    name: "tx-balance"
  datasource:
    url: jdbc:postgresql://192.168.55.195:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
server:
  port: 8082
kafka:
  bootstrap-servers: "192.168.55.195:29092"
  topic:
    balance-update-request: balance.update.request
    balance-update-success: balance.update.success
