spring:
  application:
    name: tx-command-api
  datasource:
    url: jdbc:postgresql://192.168.55.195:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


